### ISSUE TITLE
small imagenet127

### ISSUE THREAD

**Issue by xyk0058** [YUE-FAN/CoSSL#2]
Hi,

Could you also share the codes on how you preprocess dataset small_imagenet127

Many thanks,
xyk

**Comment by YUE-FAN** [comment]
Hi,

Please find the instructions on generating Small-ImageNet-127 in the folder ``prepare_small_imagenet_127``.

Should you have any further questions, please feel free to reopen the issue.

**Comment by xyk0058** [comment]
> 

Thanks~
