### ISSUE TITLE
can not reproduce experimental process.

### ISSUE THREAD

**Issue by Chaoqun-Guo** [YUE-FAN/CoSSL#3]
From the code you provided, your experimental process cannot be reproduced, and there is a data processing error using pytorch version 1.0.0 in the first step of data processing.  "python train_cifar_fix.py --ratio 2 --num_max 1500 --imb_ratio_l 150 --imb_ratio_u 150 --epoch 500 --val-iteration 500 --out ./results/cifar10/fixmatch/baseline/wrn28_N1500_r150_seed1 --manualSeed 1 --gpu 2"

**Comment by YUE-FAN** [comment]
Hi, could you please give the details of the error?

**Comment by Chaoqun-Guo** [comment]
> Hi, could you please give the details of the error?
When I try to process the cifar-10 dataset, the following problem occurs:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/30585868/179648315-8f3e533f-528f-432f-bc12-14715987c04e.png"> I googled it and said that the version of pytorch1.0.0 is out of date. I don't know how you processed the data set based on the code you provided.

**Comment by YUE-FAN** [comment]
At the first glance, it seems more like a version problem of torchvision rather than pytorch as CIFAR10 is in torchvision.datasets.
I use pytorch 1.0.0 and torchvision 0.2.2.post3 for this repo. Please check if your torchvision is compatible with your pytorch.
